# Generated by Django 5.0.6 on 2024-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_duration_course_image_course_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('registered_at', models.DateTimeField()),
            ],
        ),
    ]
