# Generated by Django 5.0.6 on 2024-06-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_students',
            name='end_date',
        ),
    ]
