# Generated by Django 5.0.6 on 2024-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_booking_students_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('is_locked', models.BooleanField(default=True)),
            ],
        ),
    ]
